tasks:
  - name: routeur_solaire_dependencies
    init: >
      pip3 install -U platformio &&
      pip3 install esptool &&
      git clean -f &&
      git fetch &&
      git pull &&
      gp sync-done bundle # 'bundle' is an arbitrary name
vscode:
  extensions:
    - ritwickdey.LiveServer    
