tasks:
  - name: routeur_solaire_dependencies
    init: >
      pip3 install -U platformio &&
      git clean -f &&
      git fetch &&
      git pull &&
      gp sync-done bundle # 'bundle' is an arbitrary name
    command: pio run -e routeur_solaire
