tasks:
  - before: pip3 install -U platformio
  - command: git clean -f
  - command: git fetch
  - command: git pull
  - command: pio clean 
  - command: pio run -t uploadfs
  - command: pio run -t upload